import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBarWithRouter from "./components/NavBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Justin's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="App MainApp">
          <NavBarWithRouter />
          <main className="main">{children}</main>
        </div>
      </body>
    </html>
  );
}
